version: '2'

services:
  nn:
    container_name: nn
    hostname: nn
    image: "sequenceiq/hadoop-docker:2.6.0"
    working_dir: /usr/local/hadoop
    ports:
      - "8088:8088"
    volumes:
      - "./artifacts/bootstrap.sh:/etc/bootstrap.sh:ro"
      - "./artifacts/start-yarn-rm.sh:/usr/local/hadoop/sbin/start-yarn.sh:ro"
      - "./artifacts/slaves:/usr/local/hadoop/etc/hadoop/slaves:ro"
      - "./artifacts/core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml:ro"
      - "./artifacts/hdfs-site.xml:/usr/local/hadoop/etc/hadoop/hdfs-site.xml:ro"
      - "./artifacts/mapred-site.xml:/usr/local/hadoop/etc/hadoop/mapred-site.xml:ro"
      - "./artifacts/yarn-site.xml:/usr/local/hadoop/etc/hadoop/yarn-site.xml:ro"
    networks:
      - default

  dn:
    image: "sequenceiq/hadoop-docker:2.6.0"
    working_dir: /usr/local/hadoop
    mem_limit: 1152m
    ports:
      - "8042"
    volumes:
      - "spark:/usr/spark-1.6.1"
      - "./artifacts/bootstrap.sh:/etc/bootstrap.sh:ro"
      - "./artifacts/start-yarn-nm.sh:/usr/local/hadoop/sbin/start-yarn.sh:ro"
      - "./artifacts/core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml:ro"
      - "./artifacts/hdfs-site.xml:/usr/local/hadoop/etc/hadoop/hdfs-site.xml:ro"
      - "./artifacts/mapred-site.xml:/usr/local/hadoop/etc/hadoop/mapred-site.xml:ro"
      - "./artifacts/yarn-site.xml:/usr/local/hadoop/etc/hadoop/yarn-site.xml:ro"
    depends_on:
      - nn
    networks:
      - default

  zeppelin:
    image: "dylanmei/zeppelin:0.6.0"
    ports:
      - "8080:8080"
    volumes:
      - "./artifacts/core-site.xml:/usr/hadoop-2.6.3/etc/hadoop/core-site.xml:ro"
      - "./artifacts/hdfs-site.xml:/usr/hadoop-2.6.3/etc/hadoop/hdfs-site.xml:ro"
      - "./artifacts/mapred-site.xml:/usr/hadoop-2.6.3/etc/hadoop/mapred-site.xml:ro"
      - "./artifacts/yarn-site.xml:/usr/hadoop-2.6.3/etc/hadoop/yarn-site.xml:ro"
    networks:
      - default

volumes:
  spark:
    driver: local

networks:
  default:
    driver: bridge
