kind: ReplicationController
apiVersion: v1
metadata:
  name: hdfs-dn-controller
  namespace: yarn-cluster
spec:
  replicas: 1
  selector:
    component: hdfs-dn
  template:
    metadata:
      labels:
        component: hdfs-dn
    spec:
      serviceAccount: yarn-cluster
      containers:
        - name: hdfs-dn
          image: sequenceiq/hadoop-docker:2.6.0
          command:
             - "/bin/bash"
             - "/tmp/hadoop-config/bootstrap.sh"
             - "-d"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "100m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          volumeMounts:
            - name: hadoop-config
              mountPath: /tmp/hadoop-config
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "curl -sf http://hosts-disco/k8s_hosts_disco > /bin/k8s_hosts_disco && chmod +x /bin/k8s_hosts_disco && /bin/k8s_hosts_disco"
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
