kind: ReplicationController
apiVersion: v1
metadata:
  name: hdfs-datanode-controller
  namespace: yarn-cluster
spec:
  replicas: 1
  selector:
    component: hdfs-datanode
  template:
    metadata:
      labels:
        component: hdfs-datanode
    spec:
      containers:
        - name: hdfs-datanode
          image: sequenceiq/hadoop-docker:2.6.0
          command:
             - "/bin/bash"
             - "/tmp/hadoop-config/bootstrap.sh"
             - "-d"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "100m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          volumeMounts:
            - name: hadoop-config
              mountPath: /tmp/hadoop-config
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
