kind: ReplicationController
apiVersion: v1
metadata:
  name: yarn-rm-controller
  namespace: yarn-cluster
spec:
  replicas: 1
  selector:
    component: yarn-rm
  template:
    metadata:
      # annotations:
      #   pod.beta.kubernetes.io/hostname: yarn-rm
      labels:
        component: yarn-rm
    spec:
      serviceAccount: yarn-cluster
      containers:
        - name: yarn-rm
          image: sequenceiq/hadoop-docker:2.6.0
          command:
             - "/bin/bash"
             - "/tmp/hadoop-config/bootstrap.sh"
             - "-d"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "100m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          volumeMounts:
            - name: hadoop-config
              mountPath: /tmp/hadoop-config
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "curl --retry 10 http://hosts-disco/start.sh | sh"
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
