kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
  namespace: yarn-cluster
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      serviceAccount: yarn-cluster
      containers:
        - name: zeppelin
          image: dylanmei/zeppelin:0.6.0
          env:
          - name: ZEPPELIN_PORT
            value: "8080"
          - name: MASTER
            value: "yarn-client"
          resources:
            requests:
              memory: "2048Mi"
              cpu: "1000m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          volumeMounts:
            - name: hadoop-config
              mountPath: /usr/hadoop-2.6.3/etc/hadoop

      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
